import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <main className="flex-grow absolute bg-cover bg-center  bg-[url('/bg.jpg')] min-h-screen flex flex-col gap-1">
        <div className="absolute inset-0 bg-black/50 backdrop-blur-sm "></div>
        <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
